remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme 
title: Notas de la materia de Inteligencia Artificial
author: Alejandro Barreras Gutiérrez

# Configuración adicional
markdown: kramdown
permalink: /:title/

# Collections para organizar las notas
collections:
  notas:
    output: true
    permalink: /notas/:name/





